##########common parameters###########
#alias
PUBLICALIAS = advpubliccert
#STOREPWD
STOREPWD = Adv@an1#23
#SUBJECT
SUBJECT = AndroidLink
#licPath
licPath = androidlink.lic
#pubPath
pubPath = /publicCerts.store